config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
 
  resources :groups do
  	resources :students
  end
  resources :teachers, :courses, :users, :groups, :students
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||=User.new
    if user.author? :author
        can :read, :all
    end

    if user.admin? :admin
        can :manage, :all
    end
  end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  	has_one :teacher
  	has_one :group
end

app/models/group.rb
class Group < ApplicationRecord
	has_many   :students
	belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :group
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %i[admin author]

  def roles=(roles)
  	#roles= [*roles].map { |r| r.to_sym }
  	self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
  	ROLES.reject do |r|
  		((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
  	end
  end

  def has_role?(role)
  	roles.include?(role.to_s)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, roles:[])}
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	#before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
	def index
		@courses = Course.all
	end

	def show
		unless @course = Course.where(id: params[:id]).first
			render "courses/show"
			render "public/404.html"
		end
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])
		@course.update_attributes(course_params)
		if @course.errors.empty?
			redirect_to course_path(@course)
		else
			render "edit"
		end
	end
	
	def new
		@course = Course.new
	end
	
	def create
		@course = Course.new(course_params)
		@course.save
		if @course.errors.empty?
			redirect_to courses_path(@course)
		else
			render "new"
		end
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy
		redirect_to action: "index"
	end
	
	private
	def course_params
		params.require(:course).permit(:name, :group_id)
	end

	#def check_if_admin
	#	render file: "public/403.html", status: 403 unless params[:author]
	#end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	#before_filter :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
	def index
		@groups = Group.all
	end

	def show
		unless @group = Group.where(id: params[:id]).first
			render "groups/show"
			render "public/404.html"
		end
	end

	def edit
		@group = Group.find(params[:id])
	end

	def update
		@group = Group.find(params[:id])
		@group.update_attributes(group_params)
		if @group.errors.empty?
			redirect_to group_path(@group)
		else
			render "edit"
		end
	end
	
	def new
		@group = Group.new
	end
	
	def create
		@group = Group.new(group_params)
		@group.save
		if @group.errors.empty?
			redirect_to groups_path(@group)
		else
			render "new"
		end
	end

	def destroy
		@group = Group.find(params[:id])
		@group.destroy
		redirect_to action: "index"
	end

	private
	def group_params
		params.require(:group).permit(:name, :course_id)
	end

	def check_if_admin
		render file: "public/403.html", status: 403 unless params[:admin]
	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	#before_filter :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
	def index
		@students = Student.all
	end

	def show
		unless @student = Student.where(id: params[:id]).first
			render "students/show"
			render "public/404.html"
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])
		@student.update_attributes(student_params)
		if @student.errors.empty?
			redirect_to student_path(@student)
		else
			render "edit"
		end
	end
	
	def new
		@student = Student.new
	end
	
	def create
		@student = Student.new(student_params)
		@student.save
		if @student.errors.empty?
			redirect_to students_path(@student)
		else
			render "new"
		end
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		redirect_to action: "index"
	end

	private
	def student_params
		params.require(:student).permit(:name, :birth_date, :school_name, :address, :passport_data, :phone_number, :group_id)
	end

	def check_if_admin
		render file: "public/403.html", status: 403 unless params[:admin]
	end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	#before_filter :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
	def index
		@teachers = Teacher.all
	end

	def show
		unless @teacher = Teacher.where(id: params[:id]).first
			render "teachers/show"
			render "public/404.html"
		end
	end

	def edit
		@teacher = Teacher.find(params[:id])
	end

	def update
		@teacher = Teacher.find(params[:id])
		@teacher.update_attributes(teacher_params)
		if @teacher.errors.empty?
			redirect_to teacher_path(@teacher)
		else
			render "edit"
		end
	end
	
	def new
		@teacher = Teacher.new
	end
	
	def create
		@teacher = Teacher.new(teacher_params)
		@teacher.save
		if @teacher.errors.empty?
			redirect_to teachers_path(@teacher)
		else
			render "new"
		end
	end

	def destroy
		@teacher = Teacher.find(params[:id])
		@teacher.destroy
		redirect_to action: "index"
	end

	private
	def teacher_params
		params.require(:teacher).permit(:name, :course_id)
	end

	def check_if_admin
		render file: "public/403.html", status: 403 unless current_user.try(:admin?)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
		unless @user = User.where(id: params[:id]).first
			render "users/show"
			render "public/404.html"
		end
	end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Добро пожаловать!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  def update
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		if @user.errors.empty?
			redirect_to user_path(@user)
		else
			render "edit"
		end
	end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/edit.html.erb
<h1>Редактирование учебного курса</h1>

<%= form_for @course do |f| %>

	<p> Название курса <br/> <%= f.text_field :name %> </p>
	
	<p> <%= f.submit "Применить изменения" %> </p>

<% end %>

app/views/courses/index.html.erb
<% if user_signed_in? || admin_signed_in? %>
<h1>Курсы дополнительного образования</h1>

<% if admin_signed_in? %>
	<div class="button">
		<button type="button" class="btn btn-default">
			<h5><%=link_to "Добавить", "courses/new" %></h5>
		</button>
	</div>
<% end %>

<% end %>
<% if @courses.empty? %>
	<b>Нет курсов</b>
<% else %>

<% if user_signed_in? || admin_signed_in? %>
	<table class="table table-striped">
		<tr>
			<th></th>
			<th>Название курса</th>
			<th>Учебная группа</th>
			<th>Преподаватель курса</th>
			<th></th>
			<th></th>
		</tr>

		<% @courses.each do |c| %>
		<tr>
			<td><%=link_to c.id, course_path(c)%></td>
			<td><%=link_to c.name, course_path(c)%></td>
			<td><%=link_to c.group.name, group_path(c)%></td>
			<td><%=link_to c.teacher.name, teacher_path(c)%></td>
			<% if admin_signed_in? %>
			<td><%=link_to edit_course_path(c) do%>	
					<i class="glyphicon glyphicon-edit"></i>		
				<% end %>
			</td>
			<td><%=link_to c, method: :delete, data: {confirm: "Точно удалить?"} do%>
					<i class="glyphicon glyphicon-remove"></i>
				<% end %>
			</td>
			<% end %>
		</tr>
					<% end %>
	<% end %>
<% end %>
	</table>
	
</br>
<% if user_signed_in? || admin_signed_in? %>
<div class = button>
	<button type="button" class= "btn btn-basic">
		<%=link_to "Преподаватели" , teachers_path%> 
		&nbsp
	</button>
	
	<button type="button" class= "btn btn-basic">
		<%=link_to "Студенты", students_path%> &nbsp
	</button>

	<button type="button" class= "btn btn-basic">
		<%=link_to "Группы", groups_path%>
	</button>
</div>
<% end %>

app/views/courses/new.html.erb
<h1>Создать новый курс</h1>

<%= form_for Course.new do |f| %>

	<p> Название курса <br/> <%= f.text_field :name %> </p>

	<p> <%= f.submit "Cоздать" %> </p>

<% end %>

app/views/courses/show.html.erb
<h1>Информация о курсе</h1>

<ul>	
	<li>ID: <%=@course.id%> </li> 
	<li>Название курса: <%=@course.name%> </li>
</ul>

<div class="button">
	<button type="button class="btn btn-basic">
		<%=link_to "Назад", courses_path%>
	</button>
</div>

app/views/groups/edit.html.erb
<h1>Редактирование учебной группы</h1>

<%= form_for @group do |f| %>

	<p> Название учебной группы <br/> <%= f.text_field :name %> </p>
	<p> Учебный курс <br/> <%= f.text_field :course_id %> </p>

	<p> <%= f.submit "Применить изменения" %> </p>

<% end %>

app/views/groups/index.html.erb
<% if user_signed_in? || admin_signed_in? %>
<h1>Учебные группы</h1>

<% if admin_signed_in? %>
	<div class="buttons">
		<button type="button" class="btn btn-default">
			<h5><%=link_to "Добавить", "groups/new" %></h5>
		</button>
	</div>
<% end %>
<% end %>

<% if @groups.empty? %>
	<b>Нет учебных групп</b>
<% else %>

<% if user_signed_in? || admin_signed_in? %>
	<table class="table table-striped">
			<tr>
				<th></th>
				<th>Учебная группа</th>
				<th>Учебный курс</th>
				<th>Студент группы</th>
				<th></th>
				<th></th>
			</tr>
		<% @groups.each do |g| %>
			<tr>
				<td><%=link_to g.id, group_path(g)%></td>
				<td><%=link_to g.name, group_path(g)%></td>
				<td><%=link_to g.course.name, course_path(g)%></td>
				<% g.students.each do |student| %>
					<td><%=link_to student.name, student_path(g)%></td>
				<% end %>
				<% if admin_signed_in? %>
				<td><%=link_to edit_group_path(g) do%>	
						<i class="glyphicon glyphicon-edit"></i>		
					<% end %>
				</td>
				<td><%=link_to g, method: :delete, data: {confirm: "Точно удалить?"} do%>
						<i class="glyphicon glyphicon-remove"></i>
					<% end %>
				</td>
				<% end %>
			</tr>
		<% end %>
<% end %>
<% end %>
	</table>
	
</br>
<% if user_signed_in? || admin_signed_in? %>
<div class="buttons">
<button type="button" class="btn btn-basic">
	<%= link_to "Курсы", courses_path %> &nbsp
</button>  
<button type="button" class="btn btn-basic">
	<%= link_to "Преподаватели", teachers_path %> &nbsp
</button>
<button type="button" class="btn btn-basic">
	<%= link_to "Студенты", students_path %>
</button>
</div>
<% end %>

app/views/groups/new.html.erb
<h1>Создать новую группу</h1>

<%= form_for Group.new do |f| %>

	<p> Название группы <br/> <%= f.text_field :name %> </p>
	<p> Учебный курс <br/> <%= f.text_field :course_id %> </p>

	<p> <%= f.submit "Cоздать" %> </p>

<% end %>

app/views/groups/show.html.erb
<h1>Информация об учебной группе</h1>

<ul>
	<li>ID: <%=@group.id%></li> 
	<li>Название группы: <%=@group.name%> </li>
	<li>Название курса: <%=@group.course.name%>  </li>	
</ul>

<div class="buttons">
<button type="button" class="btn btn-basic">
	<%=link_to "Назад", groups_path%>
</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diplomapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "navbar navbar-text">
            <% if admin_signed_in? %>
              <button type="button_auth" class ="btn btn-info btn-lg"><%=link_to "Регистрация", new_user_registration_path%>
              </button>
            <% end %>

            <% if session[:user_id].nil? %>
             <button type="button_auth" class ="btn btn-info btn-lg"><%=link_to "Вход", new_user_session_path%>
            </button>
            <% end %>

            <%if user_signed_in? ||admin_signed_in?%>
              <button type="button_auth" class ="btn btn-info btn-lg"><%=link_to "Выйти", destroy_user_session_path, method: :delete%>
              </button>
            <%end%>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
  	     <p class="notice"><%=notice%></p>
  	     <p class="alert"><%=alert%></p>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Редактирование студента</h1>

<%= form_for @student do |f| %>

	<p> Имя <br/> <%= f.text_field :name %> </p>
	<p> Дата рождения <br/> <%= f.text_field :birth_date %> </p>
	<p> Учебное заведение <br/> <%= f.text_field :school_name %> </p>
	<p> Адрес <br/> <%= f.text_field :address %> </p>
	<p> Паспортные данные <br/> <%= f.text_field :passport_data %> </p>
	<p> Номер телефона <br/> <%= f.text_field :phone_number %> </p>
	<p> Учебная группа <br/> <%= f.text_field :group_id %> </p>

	<p> <%= f.submit "Применить изменения" %> </p>

<% end %>

app/views/students/index.html.erb
<% if user_signed_in? || admin_signed_in? %>
	<h1>Cтуденты</h1> 

<% if admin_signed_in? %>
	<div class="buttons">
		<button type="button" class="btn btn-default">
			<h5><%=link_to "Добавить", "students/new" %></h5>
		</button>
	</div>
<% end %>
<% end %>

<% if @students.empty? %>
	<b>Нет студентов</b>
<% else %>

<% if user_signed_in? || admin_signed_in? %>
	<table class="table table-striped">
		<tr>
			<th></th>
			<th>Имя</th>
			<th>Дата рождения</th>
			<th>Название учебного заведения</th>
			<th>Адрес</th>
			<th>Паспортные данные</th>
			<th>Номер телефона</th>
			<th>Учебная группа</th>
			<th></th>
			<th></th>
		</tr>

	<% @students.each do |s| %>
		<tr>
			<td><%=link_to s.id, student_path(s)%></td>
			<td><%=link_to s.name, student_path(s)%></td>
			<td><%=link_to s.birth_date, student_path(s)%></td>
			<td><%=link_to s.school_name, student_path(s)%></td>
			<td><%=link_to s.address, student_path(s)%></td>
			<td><%=link_to s.passport_data, student_path(s)%></td>
			<td><%=link_to s.phone_number, student_path(s)%></td>
			<td><%=link_to s.group.name, group_path(s)%></td>
			<% if admin_signed_in? %>
			<td><%=link_to edit_student_path(s) do%>	
					<i class="glyphicon glyphicon-edit"></i>		
				<% end %>
			</td>
			<td><%=link_to s, method: :delete, data: {confirm: "Точно удалить?"} do%>
					<i class="glyphicon glyphicon-remove"></i>
				<% end %>
			</td>
			<% end %>
		</tr>
	<% end %>
	<% end %>
<% end %>
	</table>

</br>
<% if user_signed_in? || admin_signed_in? %>
<div class="buttons">
<button type="button" class="btn btn-basic">
	<%=link_to "Преподаватели" , teachers_path%> &nbsp
</button>
<button type="button" class="btn btn-basic">
	<%=link_to "Курсы", courses_path%> &nbsp
</button>
<button type="button" class="btn btn-basic">
	<%=link_to "Группы",   groups_path%>
</button>
</div>
<% end %>

app/views/students/new.html.erb
<h1>Создать нового студента</h1>

<%= form_for Student.new do |f| %>

	<p> Имя <br/> <%= f.text_field :name %> </p>
	<p> Дата рождения <br/> <%= f.text_field :birth_date %> </p>
	<p> Учебное заведение <br/> <%= f.text_field :school_name %> </p>
	<p> Адрес <br/> <%= f.text_field :address %> </p>
	<p> Паспортные данные <br/> <%= f.text_field :passport_data %> </p>
	<p> Номер телефона <br/> <%= f.text_field :phone_number %> </p>
	<p> Учебная группа <br/> <%= f.text_field :group_id %> </p>

	<p> <%= f.submit "Cоздать" %> </p>

<% end %>

app/views/students/show.html.erb
<h1>Информация о студенте</h1>

<ul>	
	<li>ID: <%=@student.id%> </li> 
	<li>Имя: <%=@student.name%> </li>
	<li>Дата рождения: <%=@student.birth_date%> </li>
	<li>Учебное заведение: <%=@student.school_name%> </li>
	<li>Адрес: <%=@student.address%> </li>
	<li>Паспортные данные: <%=@student.passport_data%> </li>
	<li>Номер телефона: <%=@student.phone_number%> </li>
	<li>Учебная группа: <%=@student.group.name%> </li>
</ul>

<div class="buttons">
<button type="button" class="btn btn-basic">
	<%=link_to "Назад", students_path%>
</button>
</div>

app/views/teachers/edit.html.erb
<h1>Редактирование преподавателя</h1>

<%= form_for @teacher do |f| %>

	<p> Имя <br/> <%= f.text_field :name %> </p>
	<p> Учебный курс <br/> <%= f.text_field :course_id %> </p>
	
	<p> <%= f.submit "Применить изменения" %> </p>

<% end %>

app/views/teachers/index.html.erb
<% if user_signed_in? || admin_signed_in? %>
<h1>Преподаватели</h1> 

<% if admin_signed_in? %>
	<div class="buttons">
		<button type="button" class="btn btn-default">
			<h5><%=link_to "Добавить", "teachers/new" %></h5>
		</button>
	</div>
<% end %>
<% end %>

<% if @teachers.empty? %>
	<b>Нет преподавателей</b>
<% else %>

<% if user_signed_in? || admin_signed_in? %>
	<table class="table table-striped">
		<tr>
			<th></th>
			<th>Имя преподавателя</th>
			<th>Курс</th>
			<th></th>
			<th></th>
		</tr>

	<% @teachers.each do |t| %>
		<tr>
			<td><%=link_to t.id, teacher_path(t)%></td>
			<td><%=link_to t.name, teacher_path(t)%></td>
			<td><%=link_to t.course.name, course_path(t)%></td>
			<% if admin_signed_in? %>
			<td><%=link_to edit_teacher_path(t) do%>	
					<i class="glyphicon glyphicon-edit"></i>		
				<% end %>
			</td>
			<td><%=link_to t, method: :delete, data: {confirm: "Точно удалить?"} do%>
					<i class="glyphicon glyphicon-remove"></i>
				<% end %>
			</td>
			<% end %>
		</tr>
	<% end %>
	<% end %>
<% end %>
	</table>

</br>
<% if user_signed_in? || admin_signed_in? %>
<div class="buttons">
<button type="button" class="btn btn-basic">
	<%=link_to "Курсы" , courses_path%> &nbsp
</button>
<button type="button" class="btn btn-basic">
	<%=link_to "Студенты", students_path%> &nbsp
</button>
<button type="button" class="btn btn-basic">
	<%=link_to "Группы",   groups_path%>
</button>
</div>
<% end %>

app/views/teachers/new.html.erb
<h1>Создать нового преподавателя</h1>

<%= form_for Teacher.new do |f| %>

	<p> Имя <br/> <%= f.text_field :name %> </p>
	<p> Учебный курс <br/> <%= f.text_field :course_id %> </p>

	<p> <%= f.submit "Cоздать" %> </p>

<% end %>

app/views/teachers/show.html.erb
<h1>Информация о преподавателе</h1>

<ul>
	
	<li>ID: <%=@teacher.id%> </li>  
	<li>Имя: <%=@teacher.name%> </li>
	<li>Курс: <%=@teacher.course.name%></li>

</ul>

<div class="button">
<button type="button" class="btn btn-basic">
	<%=link_to "Назад", teachers_path%>
</button>
</div>

app/views/users/edit.html.erb
<h1>Обновить профиль</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Сохранить изменения", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Все пользователи</h1>

<ul class="users">
  <% @users.each do |user| %>
    <table class="table-striped">
    	<tr>
    		<th>ID</th>
    		<th>Email</th>
    	</tr>
    	<tr>
    		<td><%= link_to user.id, users_path%></td>
      		<td><%= link_to user.email, users_path %></td>
    	</tr>
    </table>
  <% end %>
</ul>

</br>
<% if admin_signed_in? %>
<div class = button>
	<button type="button" class= "btn btn-basic">
		<%=link_to "Преподаватели" , teachers_path%> 
		&nbsp
	</button>
	
	<button type="button" class= "btn btn-basic">
		<%=link_to "Студенты", students_path%> &nbsp
	</button>

	<button type="button" class= "btn btn-basic">
		<%=link_to "Группы", groups_path%>
	</button>

	<button type="button" class= "btn btn-basic">
		<%=link_to "Курсы", courses_path%>
	</button>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Новый пользователь</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Создать", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Информация о пользователе</h1>

<ul class="user">
  <% @user.each do |user| %>
    <li>
      Имя: <%=link_to user.name, user_path %>
      Email: <%=link_to user.email, user_path %>
    </li>
  <% end %>
</ul>

<div class="button">
	<button type="button class="btn btn-basic">
		<%=link_to "Назад", users_path%>
	</button>
</div>